"""Markdown export for crew runs.

Renders a single, well-organized .md file suitable for handing off to a
development tool (Claude Code, Antigravity, etc.). Structured artifacts
(market_research and stitch_design JSON blobs) are converted into proper
markdown sections instead of dumped as raw JSON, so a downstream LLM gets
clean prose to reason over and a human can scan it.
"""

from __future__ import annotations

import json
import re
from datetime import datetime
from typing import Iterable

import models


# Stable section order matching the canonical crew flow. The actual outputs
# might arrive in a different order if callbacks land out-of-sequence; we
# present them in the crew's logical order regardless.
CANONICAL_ORDER = [
    "Market Discovery Researcher",
    "Lead Product Manager",
    "Lead AI Systems Architect",
    "Senior Systems Engineer",
    "AI Integration Specialist",
    "Lead UX/UI Designer",
    "Chief Information Security Officer (CISO)",
]


def slugify(value: str) -> str:
    """Lowercase-dash slug suitable for a filename."""
    value = (value or "").lower().strip()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value or "export"


def filename_for_run(project: models.Project, run: models.CrewRun) -> str:
    date = (run.completed_at or run.started_at or datetime.utcnow()).strftime("%Y-%m-%d")
    return f"{slugify(project.title)}-run-{run.id}-{date}.md"


def render_run_markdown(
    project: models.Project,
    run: models.CrewRun,
    outputs: Iterable[models.AgentOutput],
    requirements: Iterable[models.Requirement] | None = None,
) -> str:
    """Build the full markdown document for a crew run."""
    parts: list[str] = []
    parts.append(_render_header(project, run))
    parts.append(_render_brief(project, requirements))

    # Sort outputs by canonical order, then by id for anything unexpected.
    output_list = list(outputs)
    order_index = {name: i for i, name in enumerate(CANONICAL_ORDER)}
    output_list.sort(key=lambda o: (order_index.get(o.agent_name, 999), o.id))

    for output in output_list:
        parts.append(_render_section(output))

    parts.append(_render_footer())
    return "\n\n".join(p for p in parts if p).strip() + "\n"


# ----------------------------------------------------------------------------
# Section rendering
# ----------------------------------------------------------------------------


def _render_header(project: models.Project, run: models.CrewRun) -> str:
    started = run.started_at.strftime("%Y-%m-%d %H:%M UTC") if run.started_at else "—"
    completed = run.completed_at.strftime("%Y-%m-%d %H:%M UTC") if run.completed_at else "—"
    return (
        f"# {project.title}\n\n"
        f"> Generated by AI Architect Studio · Crew run #{run.id} · {started}\n\n"
        f"| | |\n"
        f"|---|---|\n"
        f"| **Project** | {project.title} |\n"
        f"| **Status** | {run.status} |\n"
        f"| **Started** | {started} |\n"
        f"| **Completed** | {completed} |\n"
        f"| **Model** | {project.llm_model or 'default'} |\n"
    )


def _render_brief(project: models.Project, requirements: Iterable[models.Requirement] | None) -> str:
    parts = ["## Brief"]
    if project.description:
        parts.append(project.description.strip())
    req_list = [r.content for r in (requirements or []) if r and r.content and r.content.strip()]
    if req_list:
        parts.append("### Additional requirements")
        parts.append("\n\n".join(req_list))
    if not project.description and not req_list:
        parts.append("_No brief recorded._")
    return "\n\n".join(parts)


def _render_section(output: models.AgentOutput) -> str:
    if output.artifact_type == "market_research":
        return _render_market_research(output)
    if output.artifact_type == "stitch_design":
        return _render_stitch_design(output)
    return _render_text(output)


def _render_text(output: models.AgentOutput) -> str:
    title = f"## {output.agent_name}"
    content = (output.output_content or "_(no output)_").strip()
    return f"{title}\n\n{content}"


def _try_parse_json(content: str) -> dict | None:
    """Parse a JSON payload that may be wrapped in fenced markdown."""
    if not content:
        return None
    candidate = content.strip()
    fence = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", candidate)
    if fence:
        candidate = fence.group(1).strip()
    try:
        obj = json.loads(candidate)
        return obj if isinstance(obj, dict) else None
    except (json.JSONDecodeError, TypeError):
        return None


# ----- Market research ------------------------------------------------------


def _render_market_research(output: models.AgentOutput) -> str:
    data = _try_parse_json(output.output_content)
    if not data:
        # Fall back to verbatim text so the user still gets something.
        return _render_text(output)

    lines = [f"## Market Discovery Research"]

    insights = data.get("key_insights_for_architecture") or []
    if insights:
        lines.append("### Key insights for the team")
        for item in insights:
            lines.append(f"- {item}")

    icp = data.get("icp") or {}
    if icp:
        lines.append("### Ideal customer profile")
        if icp.get("primary_persona"):
            lines.append(f"**Primary persona.** {icp['primary_persona']}")
        alts = icp.get("alternative_personas") or []
        if alts:
            lines.append("**Alternative personas**")
            for p in alts:
                lines.append(f"- {p}")
        jtbd = icp.get("jobs_to_be_done") or []
        if jtbd:
            lines.append("**Jobs to be done**")
            for j in jtbd:
                job = j.get("job", "")
                cur = j.get("current_alternative", "")
                trig = j.get("trigger", "")
                lines.append(f"- **{job}**")
                if cur:
                    lines.append(f"  - Today they: {cur}")
                if trig:
                    lines.append(f"  - Switches when: {trig}")

    sizing = data.get("market_sizing") or {}
    if sizing:
        lines.append("### Market sizing")
        for key, label in (("tam", "TAM"), ("sam", "SAM"), ("som", "SOM"), ("growth_rate", "Growth rate")):
            if sizing.get(key):
                lines.append(f"- **{label}** — {sizing[key]}")
        if sizing.get("notes"):
            lines.append(f"\n_Notes: {sizing['notes']}_")

    landscape = data.get("competitive_landscape") or []
    if landscape:
        lines.append("### Competitive landscape")
        for c in landscape:
            name = c.get("name", "Unknown")
            url = c.get("url")
            head = f"**{name}**" + (f" ([site]({url}))" if url else "")
            lines.append(f"- {head}")
            if c.get("positioning"):
                lines.append(f"  - Positioning: {c['positioning']}")
            if c.get("weakness"):
                lines.append(f"  - Weakness: {c['weakness']}")

    tree = data.get("opportunity_tree") or {}
    if tree:
        lines.append("### Opportunity tree")
        if tree.get("outcome"):
            lines.append(f"**Outcome:** {tree['outcome']}")
        for opp in tree.get("opportunities") or []:
            lines.append(f"#### {opp.get('name', 'Opportunity')}")
            if opp.get("evidence"):
                lines.append(f"_Evidence:_ {opp['evidence']}")
            subs = opp.get("sub_opportunities") or []
            if subs:
                lines.append("**Sub-opportunities**")
                for s in subs:
                    lines.append(f"- {s}")
            sols = opp.get("candidate_solutions") or []
            if sols:
                lines.append("**Candidate solutions**")
                for s in sols:
                    lines.append(f"- {s}")

    citations = data.get("citations") or []
    if citations:
        lines.append("### Sources")
        for c in citations:
            lines.append(f"- {c}")

    return "\n\n".join(lines)


# ----- Stitch design --------------------------------------------------------


def _render_stitch_design(output: models.AgentOutput) -> str:
    data = _try_parse_json(output.output_content)
    if not data:
        return _render_text(output)

    lines = [f"## {output.agent_name} — UX Design"]
    if data.get("design_rationale"):
        lines.append(data["design_rationale"])

    screens = data.get("screens") or []
    if screens:
        lines.append("### Screens")
        for i, s in enumerate(screens, start=1):
            name = s.get("name") or f"Screen {i}"
            desc = s.get("description") or ""
            html_url = s.get("html_url")
            shot_url = s.get("screenshot_url")
            lines.append(f"{i}. **{name}**" + (f" — {desc}" if desc else ""))
            if html_url:
                lines.append(f"   - HTML: {html_url}")
            if shot_url:
                lines.append(f"   - Screenshot: {shot_url}")

    theme = data.get("theme") or {}
    if theme:
        lines.append("### Design system")
        for key, label in (("primary_color", "Primary color"), ("accent_color", "Accent color"), ("font_family", "Font family")):
            if theme.get(key):
                lines.append(f"- **{label}:** {theme[key]}")
        if theme.get("notes"):
            lines.append(f"\n_Notes: {theme['notes']}_")

    if data.get("stitch_project_id"):
        lines.append(f"_Stitch project id: `{data['stitch_project_id']}`_")

    return "\n\n".join(lines)


# ----- Footer ---------------------------------------------------------------


def _render_footer() -> str:
    return (
        "---\n\n"
        "## How to use this brief\n\n"
        "This document was generated by **AI Architect Studio**. Hand it to a coding agent "
        "(Claude Code, Antigravity, Cursor, etc.) as the initial project brief — each section "
        "above is the deliverable from a specialized agent in the crew. Use the Architect and "
        "Systems Engineer sections to scaffold the project, the AI Integration section to wire "
        "up AI features, the UX section for screens and design tokens, and the CISO section as "
        "your initial security checklist."
    )
